version: '2'

services:
  db:
    image: mdillon/postgis:latest
    restart: always
    env_file:
     - .env
    ports:
     - "5432:5432"

  backend:
    entrypoint: ["./wait-for-it.sh", "db:5432","--","backend/bin/entry"]
    build: ./backend/
    command: bundle exec rails s -p 3003 -b '0.0.0.0'
    volumes:
     - .:/myapp
    ports:
     - '3003:3003'
    depends_on:
     - db
    env_file:
     - .env

  frontend:
    build:
      context: ./frontend/
    depends_on:
      - backend
    command: npm start
    volumes:
      - ./frontend/
    ports:
      - "3000:3000"